spring:
  application:
    name: JHW-JDBC-DATA
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: den27lad27
    username: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework: OFF

app:
  table:
    size:
      all: 5
      operators: ${app.table.size.all}
      orders: ${app.table.size.all}
      tasks: ${app.table.size.all}
      phones: ${app.table.size.all}
      histories: ${app.table.size.all}
      clients: ${app.table.size.all}

